version: '3.8'
services:
  neutron-node:
    image: neutron-node
    command: >
      /bin/bash -c '
        #!/bin/bash
        set -e

        # initialize the chain state
        bash /opt/neutron/network/init.sh
        bash /opt/neutron/network/init-neutrond.sh

        # run chain
        echo "Starting $$CHAINID..."
        neutrond start                             \
            --log_level "$$LOG_LEVEL"              \
            --home "./data/$$CHAINID"              \
            --pruning=nothing                      \
            --grpc.address="0.0.0.0:$$GRPCPORT"    \
            --grpc-web.address="0.0.0.0:$$GRPCWEB"
      '
    container_name: neutron-node
    volumes:
      - data:/opt/neutron/data
    ports:
      - 1317:1317
      - 26657:26657
      - 26656:26656
      - 8090:9090
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-warn}
      - CHAINID=${CHAIN_ID:-test-1}
      - GRPCPORT=${GRPC_PORT:-9090}
      - GRPCWEB=${GRPC_WEB:-9091}
    networks:
      - neutron-testing

  dex-trading-bot:
    build:
      context: .
    depends_on:
      - "neutron-node"
    environment:
      - CHAIN_ID=${CHAIN_ID:-test-1}
      - NEUTROND_NODE=neutron-node
      - RPC_ADDRESS=${RPC_ADDRESS:-http://neutron-node:26657}
      - API_ADDRESS=${API_ADDRESS:-http://neutron-node:1317}
      - TRADE_DURATION_SECONDS=${TRADE_DURATION_SECONDS:-}
      - TRADE_FREQUENCY_SECONDS=${TRADE_FREQUENCY_SECONDS:-60}
      - GAS_ADJUSTMENT=${GAS_ADJUSTMENT:-1.5}
      - GAS_PRICES=${GAS_PRICES:-0.0025untrn}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - neutron-testing

volumes:
  data:
    name: neutron-testing-data
    external: false

networks:
  neutron-testing:
    name: neutron-testing
    external: false
